# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw11.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 800)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 100, 28, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(737, 79, 16, 52))
        self.widget_3.setStyleSheet("font-size: 16px;")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 491, 221))
        self.label_2.setStyleSheet("background :url(:/shu.jpeg)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(210, 140, 260, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(9, 63, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(490, 0, 465, 131))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.save_button = QtWidgets.QPushButton(self.widget1)
        self.save_button.setStyleSheet("QPushButton {\n"
"                background-color: #093f73;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                display: inline-block;\n"
"                font-size: 16px;\n"
"                margin: 4px 2px;\n"
"                cursor: pointer;\n"
"                border-radius: 8px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #45a049;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #3e8e41;\n"
"            }")
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 1, 2, 1, 1)
        self.channel_operation_label = QtWidgets.QLabel(self.widget1)
        self.channel_operation_label.setStyleSheet("font-size: 16px;")
        self.channel_operation_label.setObjectName("channel_operation_label")
        self.gridLayout.addWidget(self.channel_operation_label, 0, 0, 1, 1)
        self.db_button = QtWidgets.QPushButton(self.widget1)
        self.db_button.setStyleSheet("QPushButton {\n"
"                background-color: #093f73;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                display: inline-block;\n"
"                font-size: 16px;\n"
"                margin: 4px 2px;\n"
"                cursor: pointer;\n"
"                border-radius: 8px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #45a049;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #3e8e41;\n"
"            }")
        self.db_button.setObjectName("db_button")
        self.gridLayout.addWidget(self.db_button, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setStyleSheet("font-size: 16px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.perform_operation_button = QtWidgets.QPushButton(self.widget1)
        self.perform_operation_button.setStyleSheet("QPushButton {\n"
"                background-color: #093f73;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                display: inline-block;\n"
"                font-size: 16px;\n"
"                margin: 4px 2px;\n"
"                cursor: pointer;\n"
"                border-radius: 8px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #45a049;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #3e8e41;\n"
"            }")
        self.perform_operation_button.setObjectName("perform_operation_button")
        self.gridLayout.addWidget(self.perform_operation_button, 0, 2, 1, 1)
        self.channel_operation_combo = QtWidgets.QComboBox(self.widget1)
        self.channel_operation_combo.setStyleSheet("QComboBox {\n"
"                background-color: #093f73;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                display: inline-block;\n"
"                font-size: 16px;\n"
"                margin: 4px 2px;\n"
"                cursor: pointer;\n"
"                border-radius: 8px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #45a049;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #3e8e41;\n"
"            }")
        self.channel_operation_combo.setObjectName("channel_operation_combo")
        self.channel_operation_combo.addItem("")
        self.channel_operation_combo.addItem("")
        self.channel_operation_combo.addItem("")
        self.gridLayout.addWidget(self.channel_operation_combo, 0, 1, 1, 1)
        self.slider = QtWidgets.QSlider(self.widget1)
        self.slider.setStyleSheet("            QSlider::groove:horizontal {\n"
"                border: 1px solid #bbb;\n"
"                background: white;\n"
"                height: 10px;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"            QSlider::handle:horizontal {\n"
"                background: #093f73;\n"
"                border: 1px solid #093f73;\n"
"                width: 18px;\n"
"                margin: -5px 0;\n"
"                border-radius: 9px;\n"
"            }")
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.gridLayout.addWidget(self.slider, 1, 1, 1, 1)
        self.pause_button = QtWidgets.QPushButton(self.widget1)
        self.pause_button.setStyleSheet("QPushButton {\n"
"                background-color: #093f73;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 10px 20px;\n"
"                text-align: center;\n"
"                text-decoration: none;\n"
"                display: inline-block;\n"
"                font-size: 16px;\n"
"                margin: 4px 2px;\n"
"                cursor: pointer;\n"
"                border-radius: 8px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #45a049;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #3e8e41;\n"
"            }")
        self.pause_button.setObjectName("pause_button")
        self.gridLayout.addWidget(self.pause_button, 0, 3, 1, 1)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(960, -10, 201, 141))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.r_check = QtWidgets.QCheckBox(self.widget2)
        self.r_check.setEnabled(True)
        self.r_check.setStyleSheet("font-size: 20px;")
        self.r_check.setObjectName("r_check")
        self.verticalLayout.addWidget(self.r_check)
        self.l_check = QtWidgets.QCheckBox(self.widget2)
        self.l_check.setStyleSheet("font-size: 20px;\n"
"background_color: green")
        self.l_check.setObjectName("l_check")
        self.verticalLayout.addWidget(self.l_check)
        self.thread_status_label = QtWidgets.QLabel(Form)
        self.thread_status_label.setGeometry(QtCore.QRect(500, 140, 221, 31))
        self.thread_status_label.setStyleSheet("font-size: 16px;")
        self.thread_status_label.setObjectName("thread_status_label")
        self.packet_received_label = QtWidgets.QLabel(Form)
        self.packet_received_label.setGeometry(QtCore.QRect(500, 180, 221, 31))
        self.packet_received_label.setStyleSheet("font-size: 16px;")
        self.packet_received_label.setObjectName("packet_received_label")
        self.thd_label = QtWidgets.QLabel(Form)
        self.thd_label.setGeometry(QtCore.QRect(700, 180, 350, 31))
        self.thd_label.setStyleSheet("font-size: 16px;")
        self.thd_label.setObjectName("thd_label")
        self.snr_label = QtWidgets.QLabel(Form)
        self.snr_label.setGeometry(QtCore.QRect(700, 140, 350, 31))
        self.snr_label.setStyleSheet("font-size: 16px;")
        self.snr_label.setObjectName("snr_label")

        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1100, 70, 261, 120))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(16, 66, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1130, 10, 800, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(16, 66, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        
        
        
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "双通道音频分析仪"))
        self.save_button.setText(_translate("Form", "保存数据"))
        self.channel_operation_label.setText(_translate("Form", "双通道操作："))
        self.db_button.setText(_translate("Form", "数据库"))
        self.label.setText(_translate("Form", "Horizontal"))
        self.perform_operation_button.setText(_translate("Form", "执行操作"))
        self.channel_operation_combo.setItemText(0, _translate("Form", "加法运算"))
        self.channel_operation_combo.setItemText(1, _translate("Form", "减法运算"))
        self.channel_operation_combo.setItemText(2, _translate("Form", "不做运算"))
        self.pause_button.setText(_translate("Form", "暂停/恢复"))
        self.r_check.setText(_translate("Form", "左通道"))
        self.l_check.setText(_translate("Form", "右通道"))
        self.thread_status_label.setText(_translate("Form", "线程状态: 否"))
        self.packet_received_label.setText(_translate("Form", "收到包: 无"))
        self.thd_label.setText(_translate("Form", "THD: N/A"))
        self.snr_label.setText(_translate("Form", "SNR: N/A"))
        self.label_4.setText(_translate("Form", "综合工程设计 \n小组设计作业"))
        self.label_5.setText(_translate("Form", "上海大学"))
    def add_figure(self,Form):

        self.time_figure = plt.Figure(figsize=(5, 4), dpi=100)
        self.freq_figure = plt.Figure(figsize=(5, 4), dpi=100)
        self.time_canvas = FigureCanvas(self.time_figure)
        self.freq_canvas = FigureCanvas(self.freq_figure)
        self.ax_time = self.time_figure.add_subplot(111)  # 创建时域子图
        self.ax_freq = self.freq_figure.add_subplot(111)  # 创建频域子图
        # layout.addWidget(self.time_canvas)
        # layout.addWidget(self.freq_canvas)
        # layout.setGeometry(QtCore.QRect(0, 0, 300, 200))
        # self.setLayout(layout)

        Form.setObjectName("Form")
        #Form.resize(800, 600)
        Form.setFixedSize(1400, 800)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget2 = QtWidgets.QWidget(self.widget1)
        self.widget2.setObjectName("widget2")
        horizontalLayout = QtWidgets.QHBoxLayout()
        ##############################################################################
        horizontalLayout.setContentsMargins(0,220, 0, 0)
        horizontalLayout.addWidget(self.time_canvas)
        self.widget_2 = QtWidgets.QWidget(self.widget1)
        self.widget_2.setObjectName("widget_2")
        horizontalLayout.addWidget(self.freq_canvas)
        self.my_layout  =QtWidgets.QHBoxLayout()
        
        self.setLayout(horizontalLayout)        



    
        


